export enum WorkflowTaskType {

	Leave = 1,

	Loan = 2,

	Expense = 3,

	Appraisal = 4,

	General = 5,

	AppraisalEmployee = 6,

	AppraisalManager = 7,

	AppraisalHR = 8,

	AppraisalEmployeeReview = 9,

	AppraisalEmployeeFinalTask = 10,

	AppraisalLineManager = 11,

	AppraisalLineManagerHR = 12,
	Timesheet = 13,

	Travel = 14,

	Resignation = 15,
	ResignationTask = 16,

	AppraisalManagerOfManager = 17,
	AppraisalManagerOfManagerLineManager = 18
}

export enum Enums {
	callComesInOtherValue = <any>'50',
	operationhoursSpecifyDifferentHoursValue = <any>'30'
}

export enum OrganizationStructureCatergory {
	unit,
	div,
	sect,
	deprt,
	brnch
}
export enum AppraisalTypes {
	SelfAppraisal = 1,
	LineManager = 2,
}
export enum CompanyLookupTypes {
	Competency = 1,
	CompetencyLevel = 2,
	PersonalObjectiveCategory = 3,
	BusinessObjective = 4,
	AppraisalPeriodType = 5,
	HREmail = 6,
	ClearanceItems = 7,
	TravelType = 8,
	EnablePostApproval = 9,
	InsuranceClass = 10,
	HiringPriority=11,
	InterviewRating=12,
	CompetencyCategory=13,

	EmployeeCodeAutoGenerated=16,
	EmployeeCodeAutoGeneratedStartFrom=17,
	EmployeeCodeAutoGeneratedDigitsNumber=18,
	HrNotificationOnLeaveRequest=19,
	IgnoreAppraisalManagerOfManager=20,
	PayrollStartYear=21,
	LeaveBalanceStartMonth=22
}
export enum notificationTypeEnums {
	success = <any>'Success',
	error = <any>'Error'
}

export enum enumPermissionGroupName {
	Role = <any>'Role',
	Registration = <any>'Registration',
	User = <any>'User',
	TourClient = <any>'TourClient',
	TourLocation = <any>'TourLocation',
	TourPromotion = <any>'TourPromotion',
	TourCustomer = <any>'TourCustomer',
	TourDefaultDisposition = <any>'TourDefaultDisposition',
	AnswerPhrase = <any>'AnswerPhrase',
	CallCategory = <any>'CallCategory',
	CallCategoryTeams = <any>'CallCategoryTeams',
	CallType = <any>'CallType',
	CodeMaster = <any>'CodeMaster',
	DefaultStatus = <any>'DefaultStatus',
	Industry = <any>'Industry',
	Message = <any>'Message',
	PricingStructure = <any>'PricingStructure',
	PostalTemp = <any>'PostalTemp',
	Question = <any>'Question',
	State = <any>'State',
	TimeZone = <any>'TimeZone',
	Type = <any>'Type',
	TourDefaultWaves = <any>'TourDefaultWaves',
	TourDispositions = <any>'TourDispositions',
	TourLocationZip = <any>'TourLocationZip',
	UserDefaultSettings = <any>'UserDefaultSettings',
	UserClassification = <any>'UserClassification',
	UserBonusScale = <any>'UserBonusScale',
	UserTeam = <any>'UserTeam',
	FARReport = <any>'FARReport',
	Scripting = <any>'Scripting',
	ScriptingSections = <any>'ScriptingSections',
	CallSessions = <any>'CallSessions',
	CustomerRecordLookup = <any>'CustomerRecordLookup'
}

export enum enumPermissionName {
	CanCreate = <any>'CanCreate',
	CanEdit = <any>'CanEdit',
	CanDelete = <any>'CanDelete',
	CanView = <any>'CanView'
}

export enum defaultStatus {
	unavailable = <any>'Unavailable'
}

export enum gridDefaultSettings {
	itemsPerPage = <any>10
}

export enum defaultCallCategory {
	administration = <any>'Administration'
}

export enum workflowTypes {
	Leave = 1,
	Loan = 2,
	Expense = 3,
	Appraisal = 4,
	General = 5,
	Timesheet = 13,
	Travel = 14,
	Resignation = 15,
	Overtime = 19,
	Clearance = 20,
	EmploymentLetter = 21,
	Training = 22,
	ExternalTraining = 23,
	PostJournal = 24,
	Rejoin = 25,
	Hiring=26,
	JobOffer=27
}

export enum textualResolution {
	"[me]" = -1,
	"[manager]" = -2,
	"[manager of manager]" = -3
}

export enum workflowRequestsTypes {
	Leave = 1,
	Loan = 2,
	Expense = 3,
	General = 4,
	Appraisal = 5,
	Timesheet = 6,
	Travel = 7,
	Resignation = 8,
	Overtime = 9,
	Clearance = 10,
	EmploymentLetter = 11,
	Training = 12,
	ExternalTraining = 13,
	PostJournal=14,
	Rejoin = 15,
	Hiring=16,
}
